### ISSUE TITLE
ImagePreviewer如何监听图片VerticalDrag之后消失呢？

### ISSUE THREAD

**Issue by brandlee** [jvziyaoyao/ImageViewer#12]
1. 现在的办法，LaunchedEffect监听previewerState，如果previewerState.visible就代表着出现，否则就是消失。
2. 但是这种情况，怎么避免第一次出现的时候被误认为是消失呢？

**Comment by jvziyaoyao** [comment]
> 1. 现在的办法，LaunchedEffect监听previewerState，如果previewerState.visible就代表着出现，否则就是消失。
> 2. 但是这种情况，怎么避免第一次出现的时候被误认为是消失呢？

除了visible，还有animating、visibleTarget两个标识来标记当前状态
```
LaunchedEffect(
    key1 = previewerState.animating,
    key2 = previewerState.visible,
    key3 = previewerState.visibleTarget
) {
    // 当前是否处于动画状态
    val animating = previewerState.animating
    // 当前容器是否可见
    val visible = previewerState.visible
    // 当前动作结束后容器是否可见
    val visibleTarget = previewerState.visibleTarget
}
```

**Comment by brandlee** [comment]
> > 1. 现在的办法，LaunchedEffect监听previewerState，如果previewerState.visible就代表着出现，否则就是消失。
> > 2. 但是这种情况，怎么避免第一次出现的时候被误认为是消失呢？
> 
> 除了visible，还有animating、visibleTarget两个标识来标记当前状态
> 
> ```
> LaunchedEffect(
>     key1 = previewerState.animating,
>     key2 = previewerState.visible,
>     key3 = previewerState.visibleTarget
> ) {
>     // 当前是否处于动画状态
>     val animating = previewerState.animating
>     // 当前容器是否可见
>     val visible = previewerState.visible
>     // 当前动作结束后容器是否可见
>     val visibleTarget = previewerState.visibleTarget
> }
> ```

感谢，了解了，现在我的处理方式是这样的：
```
LaunchedEffect(previewerState.visibleTarget) {
    Log.d("bruce", "ImagePreviewContent: ${previewerState.visibleTarget}")
    if (previewerState.visibleTarget == false) {
        finish()
    }
}
```
