### ISSUE TITLE
ImageGallery 加载网络图片 缩放会失效, 加载本地图片则正常

### ISSUE THREAD

**Issue by yanglei9999** [jvziyaoyao/ImageViewer#27]
@Composable
fun GalleryBody() {
    val images = remember {
        mutableStateListOf(
            "https://picsum.photos/400/400",
            "https://picsum.photos/500/500",
            "https://picsum.photos/600/600",
            "https://picsum.photos/700/700",
        )
    }
    ImageGallery(
        modifier = Modifier.fillMaxSize(),
        state = rememberImageGalleryState { images.size },
        imageLoader = { index ->
            val image = images[index]
            rememberCoilImagePainter(image = image)
        },
    )
}

加载网络图片 缩放会失效, 加载本地图片则正常

**Comment by jvziyaoyao** [comment]
可能是因为Coil无法解析你的图片地址，使用其他地址的图片是正常的
```
    val images = remember {
        mutableStateListOf(
            "https://t7.baidu.com/it/u=1595072465,3644073269&fm=193&f=GIF",
            "https://t7.baidu.com/it/u=4198287529,2774471735&fm=193&f=GIF",
        )
    }
```
